// <auto-generated />
namespace Facial_Recognition_Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMyPersonMyPersonFace : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMyPersonMyPersonFace));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061734408_Add-MyPerson-MyPersonFace"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
